### ISSUE TITLE
Iterable is reserved in php7.1

### ISSUE THREAD

**Issue by brettmc** [shabbyrobe/cachet#8]
`PHP Fatal error:  Cannot use 'Iterable' as class name as it is reserved in /srv/app/vendor/shabbyrobe/cachet/src/Cachet/Backend/Iterable.php`

It looks like "iterable" became reserved in php7.1: http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.invalid-class-names

**Comment by shabbyrobe** [comment]
Thanks for reporting! Sorry if this broke your app, I should've been on to this sooner. I have pushed a new version labelled 2.0.0-beta1. I'm relying on travis to run my tests at the moment because my current development machine doesn't yet have everything I need to verify the latest build. If travis passes (and it probably won't, it rarely does!) I'll mark this as 2.0.0 stable.
